### ISSUE TITLE
how to pass custom data or use functions like dotnettojscript

### ISSUE THREAD

**Issue by peterpavles** [med0x2e/GadgetToJScript#10]
how can we pass data to constructor or use custom method like in dotnettojscript

**Comment by med0x2e** [comment]
Not sure if using a .NET stager could help in your case, for now I don’t think there is much flexibility in terms of calling .net methods with args from WSH scripts. (Deserialization gadget triggers the default constructor). btw check DotNetToJscript, it can help with that.
