### ISSUE TITLE
issues compiling

### ISSUE THREAD

**Issue by jmaravi** [med0x2e/GadgetToJScript#2]
while conipiling in visual studion2017, exe produced wont run and complain about ndesk, then it will crash

**Comment by med0x2e** [comment]
More details about the error ?

**Comment by ricardojoserf** [comment]
I compiled it using Visual Studio 2019, when executed from my Desktop folder there was an error regarding "'NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null". I tried in the folder "GadgetToJScript\bin\Debug\GadgetToJScript.exe" where Visual Studio generates the binary and now there is not any problem executing it in there. Maybe that helps @jmaravi

**Comment by ricardojoserf** [comment]
I think the error only appears when the file "NDesk.Options.dll" is not in the same folder as the GadgetToJScript binary, probably that was the problem that @jmaravi had. I hope it helps!
